Move shell completion scripts to their own directory
dbrgn/tealdeer pull request #259
Opened 2022-01-17 19:04 UTC by SimplyDanny

The names of the scripts are unchanged. We could rename them to the scheme used by clap-generate to be prepared. 😉 What do you think?

Is there something else to update? Scripts? Documentation?

2022-01-19 22:24 UTC, niklasmohrin commented
There is a mention of the bash and fish completion files in `Cargo.toml`, I am not sure why though :thinking: @dbrgn ?

Other than that, I can't find any other places

There should definitely be a mention in `CHANGELOG.md`, but this will be added whenever we release the next time. I am not sure if we need to explicitly notify package maintainers about the change, if we mention it in the changelog - but that is a task for us, not you :)

2022-01-19 22:47 UTC, dbrgn commented
Could you also update the `upload-completions` job in `.github/workflows/release.yml`?

> There is a mention of the bash and fish completion files in `Cargo.toml`, I am not sure why though 🤔 @dbrgn ?

Hm, I think those could/should be removed as well.

2022-01-19 22:48 UTC, dbrgn requested changes

2022-01-19 22:48 UTC, dbrgn commented on docs/src/installing.md
> +Just copy them to their designated locations:
```suggestion
Just copy them to their designated location:
```

2022-01-19 23:10 UTC, SimplyDanny commented on docs/src/installing.md
> +Just copy them to their designated locations:
Changed.

2022-01-19 23:13 UTC, niklasmohrin approved these changes

2022-01-19 23:13 UTC, SimplyDanny commented
> Could you also update the upload-completions job in .github/workflows/release.yml?

Done.

> Hm, I think those could/should be removed as well.

Done.

> The names of the scripts are unchanged. We could rename them to the scheme used by clap-generate to be prepared. 😉 What do you think?

I guess you missed this question. Shall we keep the names for now or use the ones produced by clap-generate already?

2022-01-19 23:31 UTC, niklasmohrin commented
In my opinion we should stick to the current names, _even if we had clap-generate_. The names are better suited for use in this repo and you have to copy them anyways, so renaming doesnt add any complexity then either

2022-01-20 08:10 UTC, dbrgn approved these changes

2022-01-20 08:10 UTC, merged